### ISSUE TITLE
Something wrong with Luminosity Gaming

### ISSUE THREAD

**Issue by Skaronator** [xoru/CSGO_Bot#1]
LG is twice in the Team Stats Table.

https://www.reddit.com/r/csgobetting/comments/3rtx9e/luminosity_vs_mousesports_bo3_071115_1600_cest/cwraiq1

**Comment by xoru** [comment]
Those are two different teams, but with the same name.

The inactive team has been filtered for now.

**Comment by Skaronator** [comment]
Oh okay, didn't know that.
